---
- name: Установка необходимых пакетов
  ansible.builtin.package:
    name:
      - curl
      - gnupg2
    state: present
  when: ansible_os_family == "RedHat"

- name: Добавление GPG ключа Vector
  ansible.builtin.rpm_key:
    key: https://packages.timber.io/vector/GPG-KEY-VECTOR
    state: present
  when: ansible_os_family == "RedHat"

- name: Добавление репозитория Vector
  ansible.builtin.yum_repository:
    name: vector
    description: Vector RPM packages
    baseurl: https://packages.timber.io/vector/yum/current/$basearch
    gpgcheck: yes
    gpgkey: https://packages.timber.io/vector/GPG-KEY-VECTOR
    enabled: yes
    state: present
  when: ansible_os_family == "RedHat"

- name: Установка Vector
  ansible.builtin.package:
    name: vector
    state: present

- name: Создание директории для конфигурации Vector
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Настройка конфигурации Vector из шаблона
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: '0644'
  notify: restart vector

- name: Включение и запуск службы Vector
  ansible.builtin.systemd:
    name: vector
    state: started
    enabled: yes
    daemon_reload: yes
